DROP TABLE if exists Ligue;
DROP TABLE if exists Employe;

CREATE TABLE Ligue(
    ID_LIGUE INT,
    NOM_L VARCHAR(50),
    PRIMARY KEY(ID_LIGUE)
);

CREATE TABLE Employe(
    ID_EMP INT,
    NOM_EMP VARCHAR(50),
    PRENOM_EMP VARCHAR(50),
    MDP_EMP VARCHAR(50),
    DATE_ARRIVE DATE,
    DATE_DEPART DATE,  
    ADMIN BOOLEAN,
    MAIL_EMP VARCHAR(100),
    ID_LIGUE INT,
    PRIMARY KEY(ID_EMP),
    FOREIGN KEY(ID_LIGUE) REFERENCES Ligue(ID_LIGUE)
);